name: Continuous Delivery

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Add known host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VDS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VDS
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPO_NAME: ${{ secrets.DOCKERHUB_REPO_NAME }}
          VDS_IP: ${{ secrets.VDS_IP }}
        run: |
          echo "$DOCKERHUB_TOKEN" | sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$VDS_IP "docker login --username $DOCKERHUB_USERNAME --password-stdin"
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$VDS_IP "docker pull $DOCKERHUB_USERNAME/$DOCKERHUB_REPO_NAME:latest"
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$VDS_IP "docker run -d --name aton-task-4 -p 80:80 -p 443:443 $DOCKERHUB_USERNAME/$DOCKERHUB_REPO_NAME:latest"
